# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    admin.candidato:
            class: AppBundle\Admin\Candidato
            arguments: [~, AppBundle\Entity\Candidato, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Candidato }

    admin.estado:
            class: AppBundle\Admin\Estado
            arguments: [~, AppBundle\Entity\Estado, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Estado }


    admin.consultora:
            class: AppBundle\Admin\Consultora
            arguments: [~, AppBundle\Entity\Consultora, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Consultora }
